on: [push]

jobs: 
 hello_world_job:
  runs-on: ubuntu-latest
  name: A job to say hello
  steps: 
   - name: Hello World action setup
     id: hello
     uses: nishantatgit/github-action-hello-world@v1.2
     with:
      who-to-greet: 'Nishant Kuamar'	
   - name: Get the output time
     id: outputtime
     run: echo "The time was ${{steps.hello.outputs.time}}"
