on: [push]

jobs: 
 hello_world_job:
  runs-on: ubuntu-latest
  name: A job to say hello
  steps: 
   - name: Welcome Greetings! 
     id: hello
     uses: nishantatgit/github-action-hello-world@v1.4
     with:
      who-to-greet: 'Nishant Kuamar Shreevastav'
      inputList:
        - javascript
        - HTML5
        - CSS3
        - React	
   - name: Get the output time
     id: outputtime
     run: echo "The time was ${{steps.hello.outputs.time}}"
